# Generated by Django 5.1.7 on 2025-10-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExoplanetPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(choices=[('kepler', 'Kepler'), ('tess', 'TESS'), ('k2', 'K2')], max_length=20)),
                ('model_level', models.IntegerField(default=1)),
                ('input_data', models.JSONField()),
                ('planet_probability', models.FloatField()),
                ('non_planet_probability', models.FloatField()),
                ('confidence_level', models.CharField(max_length=20)),
                ('prediction_status', models.CharField(max_length=20)),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error')], default='success', max_length=10)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Exoplanet Prediction',
                'verbose_name_plural': 'Exoplanet Predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
