# Generated by Django 5.1.7 on 2025-10-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(max_length=10)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='K2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_orbper', models.FloatField()),
                ('pl_trandur', models.FloatField()),
                ('pl_rade', models.FloatField()),
                ('pl_ratdor', models.FloatField()),
                ('pl_insol', models.FloatField()),
                ('pl_eqt', models.FloatField()),
                ('st_teff', models.FloatField()),
                ('st_rad', models.FloatField()),
                ('st_mass', models.FloatField()),
                ('st_metfe', models.FloatField()),
                ('gaia_gmag', models.FloatField()),
                ('gaia_bpmag', models.FloatField()),
                ('gaia_rpmag', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='KeplerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koi_period', models.FloatField()),
                ('koi_duration', models.FloatField()),
                ('koi_depth', models.FloatField()),
                ('koi_ror', models.FloatField()),
                ('koi_dor', models.FloatField()),
                ('koi_incl', models.FloatField()),
                ('koi_impact', models.FloatField()),
                ('koi_prad', models.FloatField()),
                ('koi_sma', models.FloatField()),
                ('koi_teq', models.FloatField()),
                ('koi_insol', models.FloatField()),
                ('koi_model_snr', models.FloatField()),
                ('koi_num_transits', models.IntegerField()),
                ('koi_max_sngle_ev', models.FloatField()),
                ('koi_steff', models.FloatField()),
                ('koi_slogg', models.FloatField()),
                ('koi_smet', models.FloatField()),
                ('koi_srad', models.FloatField()),
                ('koi_smass', models.FloatField()),
                ('koi_srho', models.FloatField()),
                ('koi_kepmag', models.FloatField()),
                ('koi_gmag', models.FloatField()),
                ('koi_rmag', models.FloatField()),
                ('koi_imag', models.FloatField()),
                ('koi_zmag', models.FloatField()),
                ('koi_jmag', models.FloatField()),
                ('koi_hmag', models.FloatField()),
                ('koi_kmag', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TESSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_orbper', models.FloatField()),
                ('pl_trandurh', models.FloatField()),
                ('pl_trandeperr1', models.FloatField()),
                ('pl_trandep', models.FloatField()),
                ('pl_rade', models.FloatField()),
                ('pl_eqt', models.FloatField()),
                ('st_teff', models.FloatField()),
                ('st_logg', models.FloatField()),
                ('st_rad', models.FloatField()),
                ('st_tmag', models.FloatField()),
                ('st_dist', models.FloatField()),
                ('st_metfe', models.FloatField()),
                ('st_mass', models.FloatField()),
                ('st_lum', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='ExoplanetPrediction',
        ),
    ]
