# Generated by Django 5.1.7 on 2025-10-04 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
        migrations.RemoveField(
            model_name='forumthread',
            name='tags',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forumthread',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main_app.forumthread'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, upload_to='team/'),
        ),
        migrations.DeleteModel(
            name='ForumTag',
        ),
    ]
