# aimodel/forms.py
from django import forms

class KeplerForm(forms.Form):
    koi_period = forms.FloatField(required=True, initial=3.45)
    koi_duration = forms.FloatField(required=True, initial=2.4)
    koi_depth = forms.FloatField(required=True, initial=400.0)
    koi_ror = forms.FloatField(required=True, initial=0.02)
    koi_dor = forms.FloatField(required=True, initial=25.0)
    koi_incl = forms.FloatField(required=True, initial=89.5)
    koi_impact = forms.FloatField(required=True, initial=0.3)
    koi_prad = forms.FloatField(required=True, initial=1.5)
    koi_sma = forms.FloatField(required=True, initial=0.05)
    koi_teq = forms.FloatField(required=True, initial=1200.0)
    koi_insol = forms.FloatField(required=True, initial=1800.0)
    koi_model_snr = forms.FloatField(required=True, initial=25.0)
    koi_num_transits = forms.FloatField(required=True, initial=15)
    koi_max_sngle_ev = forms.FloatField(required=True, initial=100.0)
    koi_steff = forms.FloatField(required=True, initial=5800)
    koi_slogg = forms.FloatField(required=True, initial=4.4)
    koi_smet = forms.FloatField(required=True, initial=0.1)
    koi_srad = forms.FloatField(required=True, initial=1.0)
    koi_smass = forms.FloatField(required=True, initial=1.0)
    koi_srho = forms.FloatField(required=True, initial=1.2)
    koi_kepmag = forms.FloatField(required=True, initial=12.3)
    koi_gmag = forms.FloatField(required=True, initial=13.0)
    koi_rmag = forms.FloatField(required=True, initial=12.8)
    koi_imag = forms.FloatField(required=True, initial=12.7)
    koi_zmag = forms.FloatField(required=True, initial=12.5)
    koi_jmag = forms.FloatField(required=True, initial=11.2)
    koi_hmag = forms.FloatField(required=True, initial=11.0)
    koi_kmag = forms.FloatField(required=True, initial=10.8)

class TESSForm(forms.Form):
    pl_orbper = forms.FloatField(required=True, initial=12.34)
    pl_trandurh = forms.FloatField(required=True, initial=3.21)
    pl_trandeperr1 = forms.FloatField(required=True, initial=0.0012)
    pl_trandep = forms.FloatField(required=True, initial=0.0021)
    pl_rade = forms.FloatField(required=True, initial=1.2)
    pl_eqt = forms.FloatField(required=True, initial=800)
    st_teff = forms.FloatField(required=True, initial=5400)
    st_logg = forms.FloatField(required=True, initial=4.5)
    st_rad = forms.FloatField(required=True, initial=0.9)
    st_tmag = forms.FloatField(required=True, initial=10.8)
    st_dist = forms.FloatField(required=True, initial=100.0)

class K2Form(forms.Form):
    pl_orbper = forms.FloatField(required=True, initial=41.688644)
    pl_trandur = forms.FloatField(required=True, initial=2.3)
    pl_rade = forms.FloatField(required=True, initial=2.355)
    pl_ratror = forms.FloatField(required=True, initial=0.022)
    st_teff = forms.FloatField(required=True, initial=5703.0)
    st_rad = forms.FloatField(required=True, initial=0.95)
    sy_pmra = forms.FloatField(required=True, initial=36.5)
    sy_pmdec = forms.FloatField(required=True, initial=-51.3)
    sy_dist = forms.FloatField(required=True, initial=179.46)
    sy_gaiamag = forms.FloatField(required=True, initial=10.86)
    sy_tmag = forms.FloatField(required=True, initial=10.40)
    sy_kepmag = forms.FloatField(required=True, initial=11.04)